export const EXCHANGES = [
  {
    id: 0,
    name: "Border X Change",
    address: "551 E San Ysidro Blvd, San Diego, CA",
    plaza: "",
    buyRate: 18.53,
    sellRate: 18.74,
    currencies: ["USD", "MXP"],
    services: ["Currency Exchange"],
    featured: false,
  },
  {
    id: 1,
    name: "Express Pawn Show & Money Exchange",
    address: "390 E San Ysidro Blvd, San Ysidro, CA",
    plaza: "",
    buyRate: 18.43,
    sellRate: 18.74,
    currencies: ["USD", "MXP", "EUR"],
    services: ["Currency Exchange", "Pawn Exchange"],
    featured: true,
    description: " Exchange currency or get loan express",
  },
  {
    id: 2,
    name: "BAJAEXCHANGE",
    address:
      "22010, Erasmo Castellanos Q. 9450, Zona Urbana Rio Tijuana, Tijuana, B.C. Plaza Del",
    plaza: "Plaza Del Zapato",
    buyRate: 18.4,
    sellRate: 18.83,
    currencies: ["USD", "MXP"],
    services: ["Currency Exchange"],
    featured: false,
  },
  {
    id: 3,
    name: "Centro Cambiaro La Mision",
    plaza: "",
    buyRate: 18.33,
    sellRate: 18.63,
    currencies: ["USD", "MXP"],
    services: ["Currency Exchange"],
    featured: false,
  },
];
